"""Initial migration

Revision ID: b65e017c3c2c
Revises: 
Create Date: 2025-07-02 22:46:04.358151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65e017c3c2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('known_user_agents', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('common_hours', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('common_hours')
        batch_op.drop_column('known_user_agents')

    # ### end Alembic commands ###
